"""change phone column to string2

Revision ID: 08c99f58e1d3
Revises: 289e64fcf045
Create Date: 2022-08-10 18:21:42.500503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c99f58e1d3'
down_revision = '289e64fcf045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
