"""change phone column to string

Revision ID: 289e64fcf045
Revises: 744ce132cb43
Create Date: 2022-08-10 18:11:59.688364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289e64fcf045'
down_revision = '744ce132cb43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
