"""create users table

Revision ID: 86238eb87d0c
Revises: 
Create Date: 2022-07-16 21:21:44.294588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86238eb87d0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pword', sa.String(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
